---
- name: recover backup
  synchronize:
    src: "{{ fworch_home }}/backup_importer/importer"
    dest: "{{ fworch_home }}"
  delegate_to: "{{ inventory_hostname }}"
  listen: "importer handler"
  when: importer_handler_guard == "start"
  become: true

- name: delete backup
  file:
    state: absent
    path: "{{ fworch_home }}/backup_importer"
  listen: "importer handler"
  become: true
    
- name: fail message
  debug:
    msg:
    - "An error occured during the upgrade of role {{ role_name }}"
    - "Please restart the server {{ inventory_hostname }}"
    - "Try to upgrade {{ product_name }} later or contact the support support@cactus.de"
  listen: "importer handler"
  when: importer_handler_guard == "start"
