- debug: 
    msg:
      - "running v5.7.1 upgrade script"

- name: cp hasura cli from old /usr/local/bin dir to fworch_home/api/bin
  copy:
    src: "/usr/local/bin/hasura"
    dest: "{{ api_hasura_cli_bin }}"
    remote_src: true
  when: installation_mode == "upgrade"
  become: true
  ignore_errors: true

# initially cp current api_metadata to fworch_home/api
- name: download {{ api_hasura_version }} hasura cli binary
  get_url:
    url: "https://github.com/hasura/graphql-engine/releases/download/{{ api_hasura_version }}/cli-hasura-linux-amd64"
    dest: "{{ api_hasura_cli_bin }}"
    force: true
    mode: "0755"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_group }}"
  environment: "{{ proxy_env }}"
  become: true
  when: not api_cli_check.stat.exists 
