- block:
  - name: create api documentation using 2fd/graphdoc - install npm
    package:
      name: npm

  - name: create api documentation using 2fd/graphdoc - install graphdoc
    npm:
      name: "@2fd/graphdoc"
      global: true

  environment: "{{ proxy_env }}"
  become: true

- name: create api documentation using 2fd/graphdoc
  shell: "export NODE_OPTIONS='--max-old-space-size=4096' && graphdoc -x 'x-hasura-admin-secret: {{ api_hasura_admin_secret }}' --force -e https://{{ api_network_listening_ip_address }}:{{ api_port }}/v1/graphql -o {{ ui_start_dir }}/wwwroot/api_schema"
  become: true
  become_user: "{{ fworch_user }}"
