- name: Reload service systemctl
  systemd:
    daemon_reload: true
  listen: "restart daemons"
  become: true

- name: restart webhook service 
  service:
    name: fworch-webhook-receiver
    state: restarted       
  listen: "restart daemons"
  become: true
