- name: copy middleware server systemd service script
  template:
    src: fworch-middleware.service.j2
    dest: "/lib/systemd/system/{{ middleware_service_name }}.service"
    backup: true
    mode: "0644"
    owner: "root"
  become: true
  environment: "{{ proxy_env }}"

- name: publish middlewareserver
  command: "dotnet publish --no-self-contained -c {{ dotnet_mode }} -o {{ middleware_server_start_dir }}/bin/{{ dotnet_mode }}/net{{ dotnet_version }}"
  args:
    chdir: "{{ middleware_server_start_dir }}"
  become: true
  become_user: "{{ fworch_user }}"
  environment: "{{ proxy_env }}"
  register: publish_result

- name: fail if publish returned an error
  fail:
    msg: "could not publish middleware server successfully: {{ publish_result }}"
  when: publish_result.rc != 0

- name: make middleware service run at host startup
  systemd:
    name: "{{ middleware_service_name }}"
    enabled: true
  become: true

  # not starting the server as the api is not ready yet
  # we will restart the middlewareserver later 
