- name: set add mode for creating ldap tree
  set_fact:
    ldif_changetype: add

- name: copy the ldif templates to system
  template:
    src: "{{ item }}"
    dest: "{{  middleware_ldif_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    force: true
    owner: "{{ fworch_user }}"
    group: "{{ fworch_group }}"
  with_fileglob:
    - ../templates/ldif_files/*.j2
  become: true

- name: add tree
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -w {{ ldap_manager_pwd }} -x -f {{  middleware_ldif_dir }}/tree_{{ item }}.ldif"
  loop:
    - level_0
    - level_1
    - level_2
    - systemusers
    - roles
    - tenant0
    - operators
  # ignore errors only when re-installing on a system
