---
- block:
  - name: create sample ldap database directory
    file:
      path: "/var/lib/ldap/{{ sample_ldap_domain_name }}/"
      state: directory
      owner: "{{ openldap_server_user }}"
      group: "{{ openldap_server_user }}"

  - name: Create the DB_CONFIG file
    copy:
      src: DB_CONFIG
      dest: /var/lib/ldap/{{ sample_ldap_domain_name }}/DB_CONFIG
      owner: "{{ openldap_server_user }}"
      group: "{{ openldap_server_user }}"

  - name: copy the ldif templates to system
    template:
      src: "{{ item }}"
      dest: "{{ middleware_ldif_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
      force: true
    with_fileglob:
      - ../templates/*.j2

  - name: add new sample database to ldap
    command: "ldapmodify -H {{ openldap_url }} -D cn=config -w {{ ldap_manager_pwd }} -x -f {{ middleware_ldif_dir }}/second_db.ldif"

  - name: enhance sample ldap with test users and groups
    command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -w {{ ldap_manager_pwd }} -x -f {{ middleware_ldif_dir }}/{{ item }}.ldif"
    loop:
      - ext_role
      - ext_user
      - ext_roles
      - ext_add_user

  become: true