- name: insert demo import credentials
  postgresql_query:
    db: "{{ fworch_db_name }}"
    query: >
      DO $do$ BEGIN
      IF NOT EXISTS (SELECT * FROM import_credential WHERE credential_name='credential01_demo') THEN 
      insert into import_credential
      (id,credential_name,username,secret,is_key_pair)
      VALUES (0,'credential01_demo','{{ sample_config_user }}','dummy secret',false);
      END IF; END $do$ 
  become: true
  become_user: postgres
  