- name: insert dummy test import credentials
  postgresql_query:
    db: "{{ fworch_db_name }}"
    query: >
      DO $do$ BEGIN
      IF NOT EXISTS (SELECT * FROM import_credential WHERE credential_name='{{ test_credential_name }}') THEN 
      insert into import_credential
      (id,credential_name,username,secret,is_key_pair)
      VALUES (-1,'{{ test_credential_name }}','{{ sample_config_user }}','dummy secret',true);
      END IF; END $do$ 
  become: true
  become_user: postgres
  