# this playbook sets up some sample devices with configs to play around with

- name: create demo credentials
  include_tasks: create-demo-credentials.yml
  when: add_demo_data|bool and (installation_mode=='new' or sample_role_purpose is match('test'))

- name: create test credentials
  include_tasks: create-test-credentials.yml
  when: installation_mode=='new' or sample_role_purpose is match('test')

- name: create sample devices in database
  include_tasks: create-devices.yml
  when: installation_mode=='new' or sample_role_purpose is match('test')

- name: add second ldap database
  include_tasks: add_second_ldap_db.yml
  when: (second_ldap_db | bool) and (sample_role_purpose is not match('test'))
