
- name: add postgresql repo for rpms
  get_url:
    url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ redhat_major_version}}-{{ arch }}/pgdg-redhat-repo-latest.noarch.rpm"
    dest: "/tmp/pgdg-redhat-repo-latest.noarch.rpm"
  environment: "{{ proxy_env }}"

- name: install postgresql repo
  yum:
    name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: true

- name: remove postgresql repo file
  file:
    name: /tmp/pgdg-redhat-repo-latest.noarch.rpm 
    state: absent

- name: install glibc-langpack-en for postgresql to handle utf-8
  package:
    name: glibc-langpack-en
  become: true
