- name: copy the ldif templates to system once more (this time for adding entries)
  template:
    src: "{{ item }}"
    dest: "{{ middleware_ldif_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    force: true
  with_fileglob:
    - ../templates/tree_*.j2
  become: true

- name: add tree
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -y {{ ldap_manager_pwd_file }} -x -f {{ middleware_ldif_dir }}/tree_{{ item }}.ldif"
  loop:
    - sample_tenants
    - sample_operators
    - sample_groups
  become: true

# only add roles and groups when not testing to avoid resudue from tests
- name: add tree
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -y {{ ldap_manager_pwd_file }} -x -f {{ middleware_ldif_dir }}/tree_{{ item }}.ldif"
  loop:
    - roles_for_sample_operators
    - groups_for_sample_operators
  become: true
  when: sample_role_purpose is not match('test')
