- name: fetch EPEL
  get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ redhat_major_version }}.noarch.rpm"
    dest: "/tmp/epel-release-latest-{{ redhat_major_version }}.noarch.rpm"
  environment: "{{ proxy_env }}"

- name: add EPEL repos
  yum:
    name: "/tmp/epel-release-latest-{{ redhat_major_version }}.noarch.rpm"
    state: present

- name: remove file EPEL repo
  file:
    name: "/tmp/epel-release-latest-{{ redhat_major_version }}.noarch.rpm"
    state: absent

- name: enable repo via subscription manager
  rhsm_repository:
    name: "codeready-builder-for-rhel-{{ redhat_major_version }}-{{ arch }}-rpms"
  environment: "{{ proxy_env }}"
  become: true

- name: setting default locale in /etc/profile
  blockinfile:
    path: /etc/profile
    block: >
      export LANG="en_US.utf8"
      export LANGUAGE="en_US.utf8"
      export LC_ALL="en_US.utf8"
  become: true
