
# these tasks make sure that the docker daemon can fetch images via proxy

- name: make sure docker service dir exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755"
  become: true
  notify: "docker restart"

- name: create docker config file for proxy settings
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    backup: true
    create: true
    mode: "0644"
    block: |
      [Service]
      Environment="HTTP_PROXY={{ http_proxy }}"
      Environment="HTTPS_PROXY={{ https_proxy }}"
      Environment="NO_PROXY={{ proxy_exceptions }}"
  become: true
  notify: "docker restart"

- name: setting proxy in /etc/default/docker for eg debian
  blockinfile:
    create: true
    path:  /etc/default/docker
    block: |
      export http_proxy="{{ http_proxy }}"
      export https_proxy="{{ https_proxy }}"
      export no_proxy={{ proxy_exceptions }}
  become: true
  notify: "docker restart"
