
- name: write importer_password from install host to secrets directory
  copy:
    src: "{{ importer_password_file_on_installer }}"
    dest: "{{ importer_password_file }}"
    mode: '0600'
    owner: "{{ fworch_user }}"
    group: "{{ fworch_group }}"
  become: true
  